/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package whiteball;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Difficulty extends javax.swing.JFrame {

    /**
     * Creates new form Difficulty
     */
    public Difficulty() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        easyButton = new javax.swing.JButton();
        mediumButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();

        setTitle("Difficulty");
        setBounds(new java.awt.Rectangle(800, 300, 0, 0));
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(300, 35));
        getContentPane().setLayout(new java.awt.FlowLayout());

        easyButton.setBackground(new java.awt.Color(255, 255, 255));
        easyButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        easyButton.setText("Easy");
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(easyButton);

        mediumButton.setBackground(new java.awt.Color(255, 255, 255));
        mediumButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        mediumButton.setText("Medium (Default)");
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mediumButton);

        hardButton.setBackground(new java.awt.Color(255, 255, 255));
        hardButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        hardButton.setText("Hard");
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hardButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        WhiteBall.barLength=170;
        WhiteBall.delayTime=18;
        JOptionPane.showMessageDialog(null, "Easy difficulty has been chosen!" ,"Easy",JOptionPane.INFORMATION_MESSAGE );
        this.dispose();
    }//GEN-LAST:event_easyButtonActionPerformed

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        WhiteBall.barLength=110;
        WhiteBall.delayTime=13;
        JOptionPane.showMessageDialog(null, "Hard difficulty has been chosen!" ,"Hard",JOptionPane.INFORMATION_MESSAGE );
         this.dispose();
    }//GEN-LAST:event_hardButtonActionPerformed

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumButtonActionPerformed
        WhiteBall.barLength=140;
        WhiteBall.delayTime=15;
        JOptionPane.showMessageDialog(null, "Medium difficulty has been chosen!" ,"Medium (Default)",JOptionPane.INFORMATION_MESSAGE );
        this.dispose();
    }//GEN-LAST:event_mediumButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Difficulty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JButton mediumButton;
    // End of variables declaration//GEN-END:variables
}
