/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package whiteball;

/**
 *
 * @author user
 */
public class Leaderboards extends javax.swing.JFrame {

    /**
     * Creates new form Leaderboards
     */
    public Leaderboards() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        easyBut = new javax.swing.JButton();
        medBut = new javax.swing.JButton();
        hardBut = new javax.swing.JButton();

        setTitle("Leaderboards");
        setBounds(new java.awt.Rectangle(800, 300, 0, 0));
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        easyBut.setBackground(new java.awt.Color(255, 255, 255));
        easyBut.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        easyBut.setText("Easy Class");
        easyBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButActionPerformed(evt);
            }
        });
        jPanel1.add(easyBut);

        medBut.setBackground(new java.awt.Color(255, 255, 255));
        medBut.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        medBut.setText("Medium Class");
        medBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medButActionPerformed(evt);
            }
        });
        jPanel1.add(medBut);

        hardBut.setBackground(new java.awt.Color(255, 255, 255));
        hardBut.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        hardBut.setText("Hard Class");
        hardBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButActionPerformed(evt);
            }
        });
        jPanel1.add(hardBut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButActionPerformed
        EasyClass x=new EasyClass();
        x.setVisible(true);
    }//GEN-LAST:event_easyButActionPerformed

    private void medButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medButActionPerformed
    MediumClass x=new MediumClass();
     x.setVisible(true);
    }//GEN-LAST:event_medButActionPerformed

    private void hardButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButActionPerformed
HardClass x=new HardClass();
x.setVisible(true);
    }//GEN-LAST:event_hardButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaderboards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyBut;
    private javax.swing.JButton hardBut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton medBut;
    // End of variables declaration//GEN-END:variables
}
